[patch.crates-io]
arrow = { path = "../arrow-df54-row-group-prefetch-20260714/arrow" }
arrow-arith = { path = "../arrow-df54-row-group-prefetch-20260714/arrow-arith" }
arrow-array = { path = "../arrow-df54-row-group-prefetch-20260714/arrow-array" }
arrow-avro = { path = "../arrow-df54-row-group-prefetch-20260714/arrow-avro" }
arrow-buffer = { path = "../arrow-df54-row-group-prefetch-20260714/arrow-buffer" }
arrow-cast = { path = "../arrow-df54-row-group-prefetch-20260714/arrow-cast" }
arrow-csv = { path = "../arrow-df54-row-group-prefetch-20260714/arrow-csv" }
arrow-data = { path = "../arrow-df54-row-group-prefetch-20260714/arrow-data" }
arrow-flight = { path = "../arrow-df54-row-group-prefetch-20260714/arrow-flight" }
arrow-ipc = { path = "../arrow-df54-row-group-prefetch-20260714/arrow-ipc" }
arrow-json = { path = "../arrow-df54-row-group-prefetch-20260714/arrow-json" }
arrow-ord = { path = "../arrow-df54-row-group-prefetch-20260714/arrow-ord" }
arrow-row = { path = "../arrow-df54-row-group-prefetch-20260714/arrow-row" }
arrow-schema = { path = "../arrow-df54-row-group-prefetch-20260714/arrow-schema" }
arrow-select = { path = "../arrow-df54-row-group-prefetch-20260714/arrow-select" }
arrow-string = { path = "../arrow-df54-row-group-prefetch-20260714/arrow-string" }
parquet = { path = "../arrow-df54-row-group-prefetch-20260714/parquet" }
