[patch.crates-io]
arrow = { path = "../arrow-rs-58.3.0-source/arrow" }
arrow-arith = { path = "../arrow-rs-58.3.0-source/arrow-arith" }
arrow-array = { path = "../arrow-rs-58.3.0-source/arrow-array" }
arrow-avro = { path = "../arrow-rs-58.3.0-source/arrow-avro" }
arrow-buffer = { path = "../arrow-rs-58.3.0-source/arrow-buffer" }
arrow-cast = { path = "../arrow-rs-58.3.0-source/arrow-cast" }
arrow-csv = { path = "../arrow-rs-58.3.0-source/arrow-csv" }
arrow-data = { path = "../arrow-rs-58.3.0-source/arrow-data" }
arrow-flight = { path = "../arrow-rs-58.3.0-source/arrow-flight" }
arrow-ipc = { path = "../arrow-rs-58.3.0-source/arrow-ipc" }
arrow-json = { path = "../arrow-rs-58.3.0-source/arrow-json" }
arrow-ord = { path = "../arrow-rs-58.3.0-source/arrow-ord" }
arrow-row = { path = "../arrow-rs-58.3.0-source/arrow-row" }
arrow-schema = { path = "../arrow-rs-58.3.0-source/arrow-schema" }
arrow-select = { path = "../arrow-rs-58.3.0-source/arrow-select" }
arrow-string = { path = "../arrow-rs-58.3.0-source/arrow-string" }
parquet = { path = "../arrow-rs-58.3.0-source/parquet" }
